version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "${APP_PORT:-80}:${APP_PORT:-80}"
    env_file: .env
    volumes:
      - .:/app
    networks:
      - argocd-poc.network

networks:
  argocd-poc.network:
    driver: bridge